export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';
export const ADD_USER_CLICK = 'ADD_USER_CLICK';
export const CLEAR_USER_CLICKS_HISTORY = 'CLEAR_USER_CLICKS_HISTORY';
